[PLAT-709] allow for @[osf] test urls
brianjgeiger/markdown-it-video pull request #32
Opened 2018-03-15 19:30 UTC by Johnetordoff

## Purpose

Currently @[osf] wiki markdown tags only point to prod, this is not desirable for QA. This PR gives the markdown a bit of flexibility so QA/developers can access the staging/local servers by putting their url as the video id so while `@[osf](guid1)` will still always point to prod `@[osf](localhost:7778/render?mode=render&url=http://192.168.168.167:5000/y98tn/?action=download%26mode=render%26direct)` or `@[osf](http://mfr-staging3.io/render?mode=render&url=http://192.168.168.167:5000/y98tn/?action=download%26mode=render%26direct)` will validly point to 

## Changes

- Modifies regex and return statment to allow for raw urls.

## Side Effects

None that I know of.

## Ticket
This is going to be required to test [PLAT-709](https://openscience.atlassian.net/projects/PLAT/issues/PLAT-709)

2018-03-15 19:33 UTC, sloria commented on index.js
> +      var check_url = /http(?:s?):\/\/(?:www\.)?[a-zA-Z0-9-:.]{1,}\/render(?:\/)?[a-zA-Z0-9.&;?=:%]{1,}url=http(?:s?):\/\/[a-zA-Z0-9 -:.]{1,}\/[a-zA-Z0-9]{1,5}\/\?[a-zA-Z0-9.=:%]{1,}/
drive-by: use `lowerCamelCase`

2018-03-15 19:43 UTC, brianjgeiger requested changes
By and large looks good, but please fix the linting errors.

2018-03-15 19:43 UTC, brianjgeiger commented on test/test.js
> +  it('make sure normal iframe generates properly with link to staging', function () {
You don't need to change it for this, and I should have caught it the first go through, but in the future, if you're doing BDD for testing, it should read like a sentence. "It make sure normal iframe generates…" is a could description of the behavior of your app. Instead, something like, "It generates iframe properly when using staging mfr link" would be the way to go on that.

2018-03-19 15:03 UTC, Johnetordoff commented
@brianjgeiger linting errors fixed should be good to go.

2018-03-19 15:06 UTC, brianjgeiger commented
Almost. Remember to run `npm test` before you push to be sure.

2018-03-19 15:11 UTC, Johnetordoff commented
ug sorry about that should be a 100% now.

2018-03-19 15:13 UTC, brianjgeiger approved these changes

2018-03-19 15:13 UTC, merged